services:
  nginx:
    image: nginx:alpine
    container_name: kakeibobylaravel-nginx
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  php: # または app など、PHPのサービス名
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      args:
        # ホストのユーザーIDと一致させる（通常は1000）
        - USER_ID=1000
        - GROUP_ID=1000

  app:
    build: ./docker/php
    container_name: kakeibobylaravel-app
    user: "${UID}:${GID}"
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - mysql
    ports:
      - "8000:8000"
      - "5173:5173"

  mysql:
    image: mariadb:11.7
    container_name: kakeibobylaravel-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  mysql-data:
